import "./globals.css";
import Sidebar from "@/components/layoutComponents/Sidebar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="h-screen bg-black">
          <div className="xl:px-30 container mx-auto h-full max-w-6xl">
            <div className="grid h-full grid-cols-4">
              <Sidebar />
              <div className="lg:col-spn-2 col-span-3 border-x-[1px] border-neutral-800">
                {children}
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
